version: '3.9'

services:
  contrastive_learning:
    build: .
    image: us-central1-docker.pkg.dev/manifest-glyph-441000-g2/docker-repo/churn_prediction:1.0
    ports:
      - "8503:8503"
    volumes:
      - ./scripts/app.py:/churn_prediction/scripts/app.py
    environment:
      - STREAMLIT_SERVER_PORT=8503
      - STREAMLIT_SERVER_ADDRESS=0.0.0.0
