services:
  yolo_object_detection:
    build: .
    image: us-central1-docker.pkg.dev/manifest-glyph-441000-g2/docker-repo/yolo_object_detection:8.0
    ports:
      - "8505:8505"
    volumes:
      - ./scripts/app.py:/Yolo_object_detection/scripts/app.py
      - ./scripts/app_yolo.py:/Yolo_object_detection/scripts/app_yolo.py
      - ./data/kddcup.data.corrected:/Yolo_object_detection/data/kddcup.data.corrected
    deploy:
      resources:
        limits:
          memory: 32g  # Limit memory to 16GB
          cpus: '8.0'  # Limit CPUs to 8 cores
        reservations:
          memory: 16g 
    environment:
      - STREAMLIT_SERVER_PORT=8505
      - STREAMLIT_SERVER_ADDRESS=0.0.0.0  