version: '3.9'

services:
  automating-contracts:
    build: .
    image: us-central1-docker.pkg.dev/manifest-glyph-441000-g2/docker-repo/adverserial_robustness:2.0
    ports:
      - "8504:8504"
    volumes:
      - ./scripts/code_base.py:/adverserial_robustness/scripts/code_base.py
    environment:
      - STREAMLIT_SERVER_PORT=8504
      - STREAMLIT_SERVER_ADDRESS=0.0.0.0
