version: '3.9'

services:
  automating-contracts:
    build: .
    image: us-central1-docker.pkg.dev/manifest-glyph-441000-g2/docker-repo/automating_contracts:3.0
    ports:
      - "8503:8503"
    volumes:
      - ./scripts/app.py:/automating_contracts/scripts/app.py
    environment:
      - STREAMLIT_SERVER_PORT=8503
      - STREAMLIT_SERVER_ADDRESS=0.0.0.0
