version: '3.9'

services:
  contrastive_learning:
    build: .
    image: us-central1-docker.pkg.dev/manifest-glyph-441000-g2/docker-repo/self_supervised:2.0
    ports:
      - "8501:8501" # Maps the host port 8501 to the container port 8501
    volumes:
      - ./scripts/app.py:/contrastive_learning/scripts/app.py
    environment:
      - STREAMLIT_SERVER_PORT=8501
      - STREAMLIT_SERVER_ADDRESS=0.0.0.0
